version: "3.8"

networks:
  backend_network:
    internal: false
  frontend_network:
    driver: bridge

services:
  db:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  api:
    build: ./node-api
    container_name: node-api
    restart: always
    expose:
      - "3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_network
      - frontend_network

  frontend:
    build: ./front-end
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - frontend_network

volumes:
  db_data:
